site_name: Спецификации на АММОР
docs_dir: 'spec'
site_dir: 'public'
theme: 'material'
extra:
  palette:
    primary: 'orange'
    accent: 'light green'
markdown_extensions:
    - pymdownx.tasklist:
        custom_checkbox: true
nav:
    - 'Общая страница' : index.md
    - 'Заготовки' :
        - '3/УПММР' : '3/УПММР.md'
        - '4/ОСС' : '4/ОСС.md'
    - 'Черновики' :
        - '1/ПММВ' : '1/ПММВ.md'
#    - 'Стабильные спецификации' :
#    - 'Устаревшие спецификации' :
#    - 'Исторические спецификации' :
