@startuml
skinparam fontSize 20
actor Пользователь
|||
СиловойМодуль -[#red]> СиловойМодуль : Выключен
Пользователь -> СиловойМодуль : Нажатие кнопки
activate СиловойМодуль
СиловойМодуль -[#lightgreen]> РелеПитания : Включение
activate РелеПитания
activate МодульСетевогоУправления
СиловойМодуль -> Пользователь : Светодиод на кнопке моргает
СиловойМодуль -[#lightgreen]> СиловойМодуль : Включение
== Модули производят начальную настройку ==
МодульСетевогоУправления -[#blue]> СиловойМодуль : {"action": "found_module", "meta":{...}}
activate СиловойМодуль
СиловойМодуль -[#green]> МодульСетевогоУправления : {"status": "ok"}
deactivate СиловойМодуль
СиловойМодуль -> Пользователь : Светодиод на кнопке включён
СиловойМодуль -[#lightgreen]> СиловойМодуль : Включён
== Нормальная работа робота ==
Пользователь -> СиловойМодуль : Нажатие кнопки
СиловойМодуль -> Пользователь : Светодиод на кнопке моргает
СиловойМодуль -[#blue]> МодульСетевогоУправления : {"action": "shutdown"}
activate МодульСетевогоУправления
МодульСетевогоУправления -[#green]> СиловойМодуль : {"timeout": N}
deactivate МодульСетевогоУправления
СиловойМодуль -[#red]> СиловойМодуль : Выключение
== Модули производят процедуры по безопасному выключению ==
== Проходит N секунд ==
СиловойМодуль -> Пользователь : Светодиод на кнопке выключен
СиловойМодуль -[#red]> РелеПитания : Выключение
deactivate РелеПитания
deactivate МодульСетевогоУправления
СиловойМодуль -[#red]> СиловойМодуль : Выключен
deactivate СиловойМодуль
|||
@enduml
